---
title: "Getting Started With Git"
output:
  html_document:
    theme: darkly
    highlight: breezedark
    toc: true
    toc_float: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What Is Git?

Git is really simple: it is *version control* software that allows you to track changes within files!

Conceptually simple, but getting started with making it part of your workflow can be a chore.

## Version Control

The primary aim of version control is not only to track changes within a file, but to allow multiple people to be working on the same project. You can tell who made changes to a file, when those changes were made, and version control software can merge changes to the same file. 

Git allows for a great deal of functionality. Not only can you collaborate with Git, but you can also create separate branch of work, merge those branches together, and even *fork* a project.

## GitHub

Much like we saw with R and RStudio, Git has a friendly helper in <a href="https://github.com/">GitHub</a>. GitHub is a web-based source for hosting your projects. It is also a place to see what other people are doing!

All you need to do is to register for an account!

Some notable GitHub pages:

<a href="https://github.com/saberry">Seth Berry</a>

<a href="https://github.com/davedgd">David Dobolyi</a>

<a href="https://github.com/jplalor">John Lalor</a>

<a href="https://github.com/jjenki22">Joe Jenkins</a>

<a href="https://github.com/katliyx">Katherine Li</a>

<a href="https://github.com/yyyoment">Yun Yan</a>

<a href="https://github.com/m-clark">Michael Clark</a>

<a href="https://github.com/eddelbuettel">Dirk Eddelbuettel</a>

## Installing Git

The potential for pain starts now. Head to Git's <a href="https://git-scm.com/book/en/v2/Getting-Started-Installing-Git">download page</a>. You will likely find that this is an easy task on a Windows machine -- you can just download and install as you normally would any other piece of software. 

For a Mac, you are going to need to install something else before you can install Git. The download page recommends you install Xcode Command Line Tools, but I've never found that to be the easiest. Instead, I would go <a href="https://git-scm.com/download/mac">here</a> and step through the Homebrew process. Install Homebrew and then install Git. The binary installer is listed too. It is the easiest way! If you run into any issues, you can find the steps on <a href="https://github.com/timcharper/git_osx_installer">GitHub</a>!

## Setting Up Git

Terminal Time! On Windows, you can open up your Command Prompt; on a Mac, you can open your terminal. Once you are there, you can use the following commands:

```
git config --global user.name "Your Name"
```

```
git config --global user.email email@nd.edu
```

This is what registers whenever you *commit* something to a project. 

## Git: The Easy Way

For now, we will rock with Git in the easiest way possible -- through RStudio.

> Tools > Global Options > Git/SVN